controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

controllers/TestController.php
<?php

namespace app\controllers;

use app\models\Product;
use Yii;
use app\models\T7Q1Form;
use yii\web\Controller;

class TestController extends Controller
{
    /**
     * @return string
     */
    public function actionT7Q1()
    {
        $model = new T7Q1Form();

        if ($model->load(Yii::$app->request->post()))
            $model->validate();

        return $this->render('t7q1', [
            'model' => $model,
        ]);
    }

    /**
     * @return string
     */
    public function actionProducts()
    {
        $searchModel = new Product();
        $dataProvider = $searchModel->search(Yii::$app->request->get());

        return $this->render('products', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @return string
     */
    public function actionNullDisplay()
    {
        $searchModel = new Product();
        $dataProvider = $searchModel->search(Yii::$app->request->get());

        return $this->render('null_display', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @return string
     */
    public function actionTruncateWords()
    {
        $sourceText = '';
        for ($i = 1; $i <= 30; $i++) {
            $sourceText .= " word$i";
        }

        return $this->render('11_1', [
            'sourceText' => $sourceText,
        ]);
    }

    /**
     * @return string
     */
    public function actionIdToCamel()
    {
        $sourceText = 'created_at';

        return $this->render('11_2', [
            'sourceText' => $sourceText,
        ]);
    }

    /**
     * @return string
     */
    public function actionSlug()
    {
        $sourceText = 'Купи слона';

        return $this->render('11_3', [
            'sourceText' => $sourceText,
        ]);
    }

    /**
     * @return string
     */
    public function actionEssay()
    {
        return $this->render('essay');
    }

    /**
     * @return string
     */
    public function actionTinymce()
    {
        return $this->render('tinymce');
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\bootstrap\Html;

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="body-content">

        <div class="row">
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Задание 7. ОТОБРАЖЕНИЕ ДАННЫХ</h3>
                    </div>
                    <div class="panel-body fixed-height">
                        <h4>Вопрос 1</h4>
                        <p>Напишите свой formatter телефонного номера, формат/маска задается опционально. В базе лежит
                            числовое представление номера.</p>
                        <p>
                            <?= Html::a('Demo', ['/test/t7-q1'], ['class' => 'btn btn-primary']) ?>
                            <?= Html::a('Source', 'https://bitbucket.org/pravda1979/test-project/commits/68045839b32134fcb3148110ec1a4e90432ed371', ['class' => 'btn btn-default']) ?>
                        </p>
                        <hr>
                        <h4>Вопрос 2</h4>
                        <p>Вывести список продуктов и связанных с ними категорий используя GridView, с возможностью
                            сортировать, фильтровать. Из
                            xml https://drive.google.com/open?id=1l_idMT9M-UfBD99AHoxRhwADbmJi9oOm.</p>
                        <p>
                            <?= Html::a('Demo', ['/test/products'], ['class' => 'btn btn-primary']) ?>
                            <?= Html::a('Source', 'https://bitbucket.org/pravda1979/test-project/commits/272d97f2c82537a3ca374483268b356f7c29703d', ['class' => 'btn btn-default']) ?>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Задание 10. ВИДЖЕТЫ</h3>
                    </div>
                    <div class="panel-body fixed-height">
                        <h4>Вопрос 1</h4>
                        <p>Есть проект который разрабатывался длительное время, с большим количеством GridView. Теперь
                            клиент захотел что бы везде в списках (GridView) где выводиться "(не задано)" если column
                            возвращает null , выводилась фраза "[нет данных]". Что вы сделаете ? Укажите ссылку на
                            решение.</p>
                        <p>
                            <?= Html::a('Demo', ['/test/null-display'], ['class' => 'btn btn-primary']) ?>
                            <?= Html::a('Source', 'https://bitbucket.org/pravda1979/test-project/commits/7c536d76850e356e0eddb43cbf3840e7f38ff9c9', ['class' => 'btn btn-default']) ?>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Задание 11. ХЕЛПЕРЫ</h3>
                    </div>
                    <div class="panel-body fixed-height">
                        <h4>Вопрос 1</h4>
                        <p>Вам нужно обрезать строку, по определенному количеству слов. Что бы из 30 слов, выводилось
                            12. Приложите ссылку на код.</p>
                        <p>
                            <?= Html::a('Demo', ['/test/truncate-words'], ['class' => 'btn btn-primary']) ?>
                            <?= Html::a('Source', 'https://bitbucket.org/pravda1979/test-project/commits/ae0ae34c698be4a570c54aa7bf7627054a564543', ['class' => 'btn btn-default']) ?>
                        </p>
                        <hr>
                        <h4>Вопрос 2</h4>
                        <p>Вам нужно преобразовать строку из created_at в CreatedAt. Приложите ссылку на код.</p>
                        <p>
                            <?= Html::a('Demo', ['/test/id-to-camel'], ['class' => 'btn btn-primary']) ?>
                            <?= Html::a('Source', 'https://bitbucket.org/pravda1979/test-project/commits/d38840db35dcfaded02d4d4bf1b9d22d19f5e9b3', ['class' => 'btn btn-default']) ?>
                        </p>
                        <hr>
                        <h4>Вопрос 3</h4>
                        <p>Вам нужно строку "Купи слона" преобразовать в "Kupi slona". Приложите ссылку на код.</p>
                        <p>
                            <?= Html::a('Demo', ['/test/slug'], ['class' => 'btn btn-primary']) ?>
                            <?= Html::a('Source', 'https://bitbucket.org/pravda1979/test-project/commits/717fb81c0ea0a701ec1ba1ec3245fd64af358fa6', ['class' => 'btn btn-default']) ?>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Эссе</h3>
                    </div>
                    <div class="panel-body">
                        <p>Просмотреть видео и написать краткое эссе по каждому. Ссылку на архив приложить.</p>
                        <p>
                            <?= Html::a('Читать', ['/test/essay'], ['class' => 'btn btn-primary']) ?>
                            <?= Html::a('Скачать', ['/files/essay.zip'], ['class' => 'btn btn-default']) ?>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">TinyMCE</h3>
                    </div>
                    <div class="panel-body">
                        <p>Написать компонент визуального редактора ( на выбор ) , с возможностью его настройки и
                            установки через composer. Зарегистрировать на https://packagist.org. Приложить ссылку.</p>
                        <p>
                            <?= Html::a('Demo', ['/test/tinymce'], ['class' => 'btn btn-primary']) ?>
                            <?= Html::a('GitHub', 'https://github.com/pravda1979/yii2-tinymce', ['class' => 'btn btn-default']) ?>
                            <?= Html::a('Packagist', 'https://packagist.org/packages/pravda1979/yii2-tinymce', ['class' => 'btn btn-success']) ?>
                        </p>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>